define(['text!templates/gridBook.html'],function(template){Vue.component('gridbook',{template:template,props:['hit','category','show-wishlist-button','show-free-shipping-badge','show-new-price'],data:function(){var CartName=bwb.localize.siteSettings.CartName;return{processingAddToCart:false,addToCartPopoverTemplate:'<div class="popover popover-gridbook" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>',addToCartPopoverMarkup:'<div style="text-align:center;"><div class="cssload-loader" style="margin-top:75px;"></div></div>',addToCartPopoverButtons:'<div class="gridbook-buttons"><button name="btnGridBookKeepShopping" type="button" class="btn btn-link">Keep Shopping</button> <a href="/bag" class="btn btn-success bg-white color-secondary-2-0 bd-color-secondary-2-0"><span class="glyphicon glyphicon-shopping-cart"></span> &nbsp;View '+CartName+'</a></div>',addToCartPopoverButtonsMismatch:'<div class="gridbook-buttons"><button name="btnGridBookKeepShopping" type="button" class="btn btn-link">Keep Shopping</button> <button name="btnGridBookMismatch" type="button" class="btn btn-success bg-white color-secondary-2-0 bd-color-secondary-2-0">Add To '+CartName+'</button></div>',localize:bwb.localize.siteSettings,imageUrl:'/images/products/imageless-placeholder.png',placeHolderImageUrl:'/images/products/imageless-placeholder.png',isInView:false,cartOp:'buyused'};},computed:{CartName:function(){return bwb.localize.siteSettings.CartName;},title:function(){return this.hit.Title;},imageId:function(){return 'hitimg-'+this.hit.Isbn13;},ratingStars:function(){return bwb.product.getRatingStars(this.hit.Rating,"star");},authorString:function(){return this.hit.Authors.join(', ');},authorLinks:function(){var links=[];$.each(this.hit.Authors,function(i,author){links.push('<a href="/search/results?q='+author+'" itemprop="author">'+author+'</a>');});return links.join(', ');},conditionId:function(){return bwb.pricing.getPriceObject(this.hit,this.showNewPrice,bwb.store.state).Condition;},condition:function(){return bwb.product.getConditionString(this.conditionId);},price:function(){var priceObject=bwb.pricing.getPriceObject(this.hit,this.showNewPrice,bwb.store.state);if(priceObject){var priceAmt=priceObject?priceObject.UnitPrice:0;priceAmt=bwb.pricing.applyZoneAddIns(priceObject.Condition,priceAmt,bwb.store.state.zoneId,this.hit.Weight,priceObject.SourceLocale);priceObject.CartPrice=priceAmt;if(priceObject.Condition==1)
this.cartOp='buynew';else
this.cartOp='buyused';return bwb.localize.siteSettings.CurrencySymbol+priceObject.CartPrice;}
return "";},percentSaved:function(){if(bwb.store.state.cartCurrency!='USD')
return "";var priceObject=bwb.pricing.getPriceObject(this.hit,this.showNewPrice,bwb.store.state);if(priceObject){var priceAmt=priceObject?priceObject.UnitPrice:0;priceAmt=bwb.pricing.applyZoneAddIns(priceObject.Condition,priceAmt,bwb.store.state.zoneId,this.hit.Weight,priceObject.SourceLocale);var percentage=bwb.pricing.percentageSaved(priceObject.ListPrice,priceAmt);var hasPercentage=(percentage>10);return(hasPercentage)?"Save "+percentage+"%":"";}
return "";},productId:function(){if(this.hit.AvailableCopies.length)
return this.hit.AvailableCopies[0].ProductId;return null;},detailUrl:function(){return bwb.product.getDetailUrl(this.hit.Title,this.hit.Isbn13);},buttonId:function(){return "gridbook-"+this.category+"-"+this.hit.objectID;},buttonSelector:function(){return "#"+this.buttonId;},wishlistUrl:function(){return "/Services/AddtoWishList.aspx?titleId="+this.productId;},language:function(){return this.hit.Language;},format:function(){return this.hit.Format;},ean:function(){return this.hit.EAN;},showTruck:function(){return bwb.localize.siteSettings.CountryCode=='US'&&!this.percentSaved.length;},showPercentSaved:function(){return this.percentSaved.length;}},methods:{addToCart:function(event,mismatchPrice,mismatchConditionId){var self=this;bwb.bus.$emit('gridBook-addToCart-click',self.category);if(event)
event.preventDefault();$('[name="gridBookButton"]').not($(self.buttonSelector)).popover('hide');$(self.buttonSelector).popover('show');self.processingAddToCart=true;var ean=this.hit.EAN;var price=(mismatchPrice)?mismatchPrice:this.price;$.post("/Services/Recommendation.aspx?op="+this.cartOp,{titleId:this.productId,ean:this.hit.EAN,price:(mismatchPrice)?mismatchPrice:this.price,conditionId:(mismatchConditionId)?mismatchConditionId:this.conditionId,suffixId:0},function(r){if(r.Success){bwb.cart.getCartCount();dataLayer.push({'cartProdID':ean});dataLayer.push({'cartPrice':price});dataLayer.push({'event':'addcart'});}
$('.popover-gridbook > .popover-content').html(r.Message);$('.popover-gridbook > .popover-content .btns').html(!r.Mismatch?self.addToCartPopoverButtons:self.addToCartPopoverButtonsMismatch);$('[name="btnGridBookKeepShopping"]').click(function(){$(self.buttonSelector).popover('hide');});if(r.Mismatch){$('[name="btnGridBookMismatch"]').click(function(){self.addToCart(null,r.MismatchPrice,r.MismatchConditionId);});}
self.processingAddToCart=false;},"json");},defaultCheck:function(event){if(bwb.store.state.useOpenLibraryImages&&this.hit.Isbn13.startsWith('9')){var img=event.target;var isDefault=bwb.product.defaultImageCheck(img);if(img.src){if(isDefault===false&&img.src.indexOf('openlibrary.org')>-1){bwb.product.logMissingImage(this.hit.Isbn13);if(bwb.store.debug)console.log('%cOpenLibrary has an image for '+this.hit.Isbn13+' - '+this.hit.Title,'color: blue; font-weight: bold;');}
if(isDefault===true&&bwb.store.debug)console.log('%cOpenLibrary does not have an image for '+this.hit.Isbn13+' - '+this.hit.Title,'color: red; font-weight: bold;');}}},updateInView:function(){if(this.isInView)
return;var elem=document.getElementById(this.imageId);if(elem)
this.isInView=bwb.helpers.elementScrolledIntoView($(elem));if(this.isInView){var url=bwb.product.buildProductImageUrl(this.hit.ImageURL);var isbn13=this.hit.Isbn13;if((url==undefined||url.trim().length===0)&&isbn13)
bwb.product.findProductImageUrl(isbn13);if(url){this.imageUrl=url;}else if(bwb.store.state.useOpenLibraryImages&&isbn13.startsWith('9')){if(bwb.store.debug)console.log('%cReturning OpenLibrary image for '+isbn13,'font-weight: bold;');this.imageUrl='https://covers.openlibrary.org/b/isbn/'+isbn13+'-M.jpg';}
$(window).off("scroll",this.updateInView);}}},mounted:function(){$(this.buttonSelector).popover();this.updateInView();$(window).on("scroll",this.updateInView);}});});